- id: remove-blank-cells
  name: Remove blank cells from notebook end
  entry: remove-blank-cells
  language: python
  files: \.ipynb$
- id: lint-sql-cells
  name: Lint cells with SQL
  entry: lint-sql-cells
  language: python
  files: \.ipynb$
