- id: remove-blank-cells
  name: Remove blank cells from notebook
  entry: remove-blank-cells
  language: python
  files: \.ipynb$
- id: lint-sql-cells
  name: Lint cells with SQL
  entry: lint-sql-cells
  language: python
  files: \.ipynb$
- id: add-colophon
  name: Append copyright cell to notebook
  entry: add-colophon
  language: python
  files: \.ipynb$
- id: add-task-numbers
  name: Add / correct task numbering
  entry: add-task-numbers
  language: python
  files: \.ipynb$
- id: add-usage-guidelines
  name: Add reuse guidelines
  entry: add-usage-guidelines
  language: python
  files: \.ipynb$
- id: fix-title-headers
  name: Fix notebook titles and H1 headers
  entry: fix-title-headers
  language: python
  files: \.ipynb$
- id: add-canary
  name: Add invisible text to MD cell
  entry: add-canary
  language: python
  files: \.ipynb$
