# Modeled on https://github.com/janosh/format-ipy-cells/
name: Tests

on:
  push:
    branches: [main]
    # paths: ['**/*.py']
  pull_request:
    branches: [main]
    # paths: ['**/*.py']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install nb-hooks and test dependecies
      run: pip install .[test]
    - name: Run tests
      run: python -m pytest
